apiVersion: v1
kind: Secret
metadata:
  name: eshoponweb-secrets
  namespace: eshoponweb
type: Opaque
stringData:
  SA_PASSWORD: "@someThingComplicated1234"
  CatalogConnection: "Server=sqlserver-service;Database=Microsoft.eShopOnWeb.CatalogDb;User Id=sa;Password=@someThingComplicated1234;TrustServerCertificate=true"
  IdentityConnection: "Server=sqlserver-service;Database=Microsoft.eShopOnWeb.Identity;User Id=sa;Password=@someThingComplicated1234;TrustServerCertificate=true"