apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: eshoponweb
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: eshopwebmvc:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: eshoponweb-config
              key: ASPNETCORE_ENVIRONMENT
        - name: UseOnlyInMemoryDatabase
          valueFrom:
            configMapKeyRef:
              name: eshoponweb-config
              key: UseOnlyInMemoryDatabase
        - name: ASPNETCORE_URLS
          valueFrom:
            configMapKeyRef:
              name: eshoponweb-config
              key: ASPNETCORE_URLS
        - name: ConnectionStrings__CatalogConnection
          valueFrom:
            secretKeyRef:
              name: eshoponweb-secrets
              key: CatalogConnection
        - name: ConnectionStrings__IdentityConnection
          valueFrom:
            secretKeyRef:
              name: eshoponweb-secrets
              key: IdentityConnection
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: eshoponweb
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP